stages:
  - review

review_bot:
  stage: review
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
    - ci
  variables:
    DOCKER_DRIVER: overlay2
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - apk add --no-cache docker-compose curl
  script:
    - docker-compose up --build --abort-on-container-exit
  only:
    - merge_requests
