stages:
  - review

variables:
  CI_PROJECT_ID: $CI_PROJECT_ID
  GITLAB_TOKEN: $GITLAB_TOKEN
  OPEN_AI_KEY: $OPEN_AI_KEY

  # 리뷰 모델과 RAG 사용 여부
  REVIEW_MODEL: "OpenAI"   # "hf.co/Bllossom/llama-3.2-Korean-Bllossom-3B-gguf-Q4_K_M"로 설정시 llama 3.2 Ko 3b 모델 리뷰 가능
  RAG_FLAG: "RAG"    # "" 으로 설정하면 RAG 모드로 동작

mr_review:
  stage: review
  image: os2864/review-buddy-gpt:v0.1.1 # "os2864/review-buddy:v0.1.5" ollama도 사용하는 Docker Iamge
  only:
    - merge_requests
  script:
    - ollama serve &
    - python /app/review_buddy.py $REVIEW_MODEL $RAG_FLAG
