stages:
  - review

mr_review:
  stage: review
  image: rnrmf/mr-review-bot:latest
  variables:
    CI_PROJECT_ID: $CI_PROJECT_ID
    OPEN_AI_KEY: $OPEN_AI_KEY
  ONLY:
    - MERGE_REQUESTS
  SCRIPT:
    - ollama serve &
    - python ~/review_buddy.py