stages:
  - build
  - review

variables:
  REGISTRY: "$CI_REGISTRY_IMAGE"

build_images:
  stage: build
  image: docker:24.0.5-dind
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -f Dockerfile.ollama -t $REGISTRY/ollama:phi2 .
    - docker push $REGISTRY/ollama:phi2

    - docker build -f Dockerfile.reviewbot -t $REGISTRY/reviewbot:latest .
    - docker push $REGISTRY/reviewbot:latest
  only:
    - main

review_bot:
  stage: review
  image: docker:24.0.5-dind
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose curl
  script:
    - docker-compose pull
    - docker-compose up --abort-on-container-exit
  only:
    - merge_requests
