stages:
  - review

mr_review:
  stage: review
  image: rnrmf/mr-review-bot:latest
  variables:
    CI_PROJECT_ID: $CI_PROJECT_ID
    GITLAB_TOKEN: $GITLAB_TOKEN
    TESTENV: $TESTKEY
  only:
    - merge_requests
  script:
    - echo $TESTKEY
    - echo $TESTENV
    - ollama serve &
    - python ~/review_buddy.py