stages:
  - review

variables:
  CI_PROJECT_ID: $CI_PROJECT_ID
  GITLAB_TOKEN: $GITLAB_TOKEN
  OPEN_AI_KEY: $OPEN_AI_KEY
  REVIEW_BUDDY: $REVIEW_BUDDY

  # 리뷰 모델과 RAG 사용 여부
  REVIEW_MODEL: "OpenAI"   # llama3.2 도 가능
  RAG_FLAG: "rag"    # "rag" 로 설정하면 RAG 모드로 동작

mr_review:
  stage: review
  image: os2864/review-buddy:v0.1.3
  only:
    - merge_requests
  script:
    - echo $CI_API_V4_URL
    - ollama serve &
    - python /app/review_buddy.py $REVIEW_MODEL $RAG_FLAG
