stages:
  - review

variables:
  REGISTRY: "$CI_REGISTRY_IMAGE"

mr_review:
  stage: review
  image: rnrmf/mr-review-bot:latest
  variables:
    CI_PROJECT_ID: $CI_PROJECT_ID
  only:
    - merge_requests
  script:
    - python review_buddy.py