stages:
  - review

variables:
  CI_PROJECT_ID: $CI_PROJECT_ID
  GITLAB_TOKEN: $GITLAB_TOKEN
  OPEN_AI_KEY: $OPEN_AI_KEY

  # 리뷰 모델과 RAG 사용 여부
  REVIEW_MODEL: "llama3.2"   # "OpenAI"로 설정시 GPT-4o 리뷰 가능
  RAG_FLAG: "RAG"    # "" 으로 설정하면 RAG 모드로 동작

mr_review:
  stage: review
  image: os2864/review-buddy-gpt:v0.1.1 # "os2864/review-buddy:v0.1.3" ollama도 사용하는 Iamge
  only:
    - merge_requests
  script:
    - ollama serve &
    - python /app/review_buddy.py $REVIEW_MODEL $RAG_FLAG
