stages:
  - review

review_bot:
  stage: review
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
    - ci
  before_script:
    - apk add --no-cache docker-compose curl
  script:
    - docker-compose up --build --abort-on-container-exit
  only:
    - merge_requests
