declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_COMMUNITY_URL: string,
    NEXT_PUBLIC_COMMUNITY_CONTRIBUTE_GUIDE_URL: string,
    NEXT_PUBLIC_COMMUNITY_GITHUB_URL: string,
    NEXT_PUBLIC_COMMUNITY_GITLAB_URL: string,
    NEXT_PUBLIC_COMMUNITY_VERSION_URL: string,

    NEXT_PUBLIC_COMMIT_BUDDY_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_INTRO_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_INTELLIJ_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_INTELLIJ_HOW_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_VSCODE_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_VSCODE_HOW_URL: string,

    NEXT_PUBLIC_LINT_BUDDY_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_INTRO_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_CUTOMIZING_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_GETTINGSTARTED_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_MENUAL_URL: string,

    NEXT_PUBLIC_INTRODUCE_URL: string,
    NEXT_PUBLIC_INTRODUCE_INTRO_URL: string,
    NEXT_PUBLIC_INTRODUCE_TOOLS_URL: string,

    NEXT_PUBLIC_REVIEW_BUDDY_URL: string,
    NEXT_PUBLIC_REVIEW_BUDDY_HOWTOUSE_URL: string,
    NEXT_PUBLIC_REVIEW_BUDDY_INTRO_URL: string,

    NEXT_PUBLIC_SSAFY_CLIENT_ID: string,
    NEXT_PUBLIC_SSAFY_SECRET: string
    NEXT_PUBLIC_SSAFY_REDIRECT_URI: string

    NEXT_PUBLIC_FIRESTORE_APIKEY: string,
    NEXT_PUBLIC_FIRESTORE_AUTHDOMAIN: string,
    NEXT_PUBLIC_FIRESTORE_PROJECTID : string,
    NEXT_PUBLIC_FIRESTORE_STORAGEBUCKET: string,
    NEXT_PUBLIC_FIRESTORE_MESSAGINGSENDERID: string,
    NEXT_PUBLIC_FIRESTORE_APPID: string,
    NEXT_PUBLIC_FIRESTORE_MEASUREMENTID: string
  }
}