declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_COMMUNITY_URL: string,
    NEXT_PUBLIC_COMMUNITY_CONTRIBUTE_GUIDE_URL: string,
    NEXT_PUBLIC_COMMUNITY_GITHUB_URL: string,
    NEXT_PUBLIC_COMMUNITY_GITLAB_URL: string,
    NEXT_PUBLIC_COMMUNITY_VERSION_URL: string,

    NEXT_PUBLIC_COMMIT_BUDDY_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_INTRO_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_INTELLIJ_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_INTELLIJ_HOW_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_VSCODE_URL: string,
    NEXT_PUBLIC_COMMIT_BUDDY_VSCODE_HOW_URL: string,

    NEXT_PUBLIC_LINT_BUDDY_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_INTRO_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_CUTOMIZING_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_GETTINGSTARTED_URL: string,
    NEXT_PUBLIC_LINT_BUDDY_MENUAL_URL: string,

    NEXT_PUBLIC_INTRODUCE_URL: string,
    NEXT_PUBLIC_INTRODUCE_INTRO_URL: string,
    NEXT_PUBLIC_INTRODUCE_TOOLS_URL: string,

    NEXT_PUBLIC_REVIEW_BUDDY_URL: string,
    NEXT_PUBLIC_REVIEW_BUDDY_HOWTOUSE_URL: string,
    NEXT_PUBLIC_REVIEW_BUDDY_INTRO_URL: string,
  }
}